"""debug categories and users

Revision ID: 60df6a083ae5
Revises: fc4b39ffdf76
Create Date: 2025-03-31 14:37:34.316193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60df6a083ae5'
down_revision: Union[str, None] = 'fc4b39ffdf76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('parent_name', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'categories', ['name'])
    op.drop_constraint('categories_parent_id_fkey', 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'categories', ['parent_name'], ['name'])
    op.drop_column('categories', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key('categories_parent_id_fkey', 'categories', 'categories', ['parent_id'], ['id'])
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_column('categories', 'parent_name')
    # ### end Alembic commands ###
